# Generated by Django 5.1 on 2024-12-31 03:06

import django.db.models.deletion
import producto.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=200, null=True)),
                ('cantProdDisponible', models.IntegerField(null=True)),
                ('cant_producto_ingresada', models.IntegerField(null=True)),
                ('fecha_ingreso_producto', models.DateTimeField(auto_now_add=True)),
                ('precioProd', models.IntegerField(null=True)),
                ('ruta_img_1', models.FileField(upload_to=producto.models.upload_to_path)),
                ('ruta_img_2', models.FileField(upload_to=producto.models.upload_to_path)),
                ('ruta_img_3', models.FileField(upload_to=producto.models.upload_to_path)),
                ('detalle_producto', models.TextField(null=True)),
                ('fk_usuario_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
