# Generated by Django 5.1 on 2024-12-31 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.IntegerField(null=True)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cantidad_cuotas', models.IntegerField(null=True)),
                ('monto_total', models.IntegerField(null=True)),
                ('monto_cuota', models.IntegerField(null=True)),
                ('cod_venta', models.CharField(max_length=255, null=True)),
                ('fk_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
        ),
    ]
