# Generated by Django 5.1 on 2024-12-31 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateTimeField(auto_now_add=True)),
                ('cantProducto', models.IntegerField(null=True)),
                ('nombre_producto', models.CharField(max_length=255, null=True)),
                ('total_pagar', models.IntegerField(null=True)),
                ('numero_venta', models.CharField(max_length=255, null=True)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
